"""empty message

Revision ID: 977d0c5593e6
Revises: 94b0d12ef5de
Create Date: 2022-03-03 19:50:21.970840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977d0c5593e6'
down_revision = '94b0d12ef5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
